// Référentiel des destinations au départ de Bordeaux-Mérignac (BOD).
// dur = temps de vol indicatif ; sch = espace Schengen ; tip = depuis l'aéroport d'arrivée.
window.BOD = {
  ORIGIN: { lat: 44.828, lon: -0.715 },
  DEST: {
    LYS:{name:'Lyon',country:'France',lat:45.726,lon:5.091,tz:'Europe/Paris',dur:'1h05',sch:true,tip:"Rhônexpress jusqu'à Lyon Part-Dieu en 30 min."},
    CDG:{name:'Paris CDG',country:'France',lat:49.010,lon:2.548,tz:'Europe/Paris',dur:'1h15',sch:true,tip:"RER B jusqu'au centre de Paris en 35 min environ."},
    ORY:{name:'Paris Orly',country:'France',lat:48.723,lon:2.379,tz:'Europe/Paris',dur:'1h10',sch:true,tip:"Métro ligne 14 jusqu'au centre de Paris."},
    AMS:{name:'Amsterdam',country:'Pays-Bas',lat:52.310,lon:4.768,tz:'Europe/Amsterdam',dur:'1h50',sch:true,tip:"Train direct jusqu'à Amsterdam Centraal en 15 min."},
    LGW:{name:'Londres Gatwick',country:'Royaume-Uni',lat:51.148,lon:-0.190,tz:'Europe/London',dur:'1h35',sch:false,tip:"Gatwick Express jusqu'à Victoria en 30 min."},
    LTN:{name:'Londres Luton',country:'Royaume-Uni',lat:51.875,lon:-0.368,tz:'Europe/London',dur:'1h40',sch:false,tip:"Navette DART puis train vers St Pancras, 35 min environ."},
    MAN:{name:'Manchester',country:'Royaume-Uni',lat:53.354,lon:-2.275,tz:'Europe/London',dur:'1h50',sch:false,tip:"Train direct jusqu'à Manchester Piccadilly en 20 min."},
    MAD:{name:'Madrid',country:'Espagne',lat:40.472,lon:-3.561,tz:'Europe/Madrid',dur:'1h15',sch:true,tip:"Métro ligne 8 ou train Cercanías jusqu'au centre."},
    RAK:{name:'Marrakech',country:'Maroc',lat:31.607,lon:-8.036,tz:'Africa/Casablanca',dur:'2h40',sch:false,tip:"La médina est à 15 min en taxi."},
    MRS:{name:'Marseille',country:'France',lat:43.439,lon:5.221,tz:'Europe/Paris',dur:'1h05',sch:true,tip:"Navette jusqu'à la gare Saint-Charles en 25 min environ."},
    ALG:{name:'Alger',country:'Algérie',lat:36.691,lon:3.215,tz:'Africa/Algiers',dur:'2h00',sch:false},
    NCE:{name:'Nice',country:'France',lat:43.658,lon:7.216,tz:'Europe/Paris',dur:'1h20',sch:true,tip:"Tramway ligne 2 jusqu'au centre et au port."},
    BCN:{name:'Barcelone',country:'Espagne',lat:41.297,lon:2.078,tz:'Europe/Madrid',dur:'1h10',sch:true,tip:"Aerobús jusqu'à Plaça de Catalunya en 35 min environ."},
    IST:{name:'Istanbul',country:'Turquie',lat:41.262,lon:28.742,tz:'Europe/Istanbul',dur:'3h45',sch:false,tip:"Métro M11 ou bus Havaist vers le centre, comptez 1 h."},
    GVA:{name:'Genève',country:'Suisse',lat:46.238,lon:6.109,tz:'Europe/Zurich',dur:'1h25',sch:true,tip:"Train jusqu'à Genève Cornavin en 7 min."},
    DUB:{name:'Dublin',country:'Irlande',lat:53.421,lon:-6.270,tz:'Europe/Dublin',dur:'1h55',sch:false,tip:"Bus express jusqu'au centre en 30 min environ."},
    OPO:{name:'Porto',country:'Portugal',lat:41.248,lon:-8.681,tz:'Europe/Lisbon',dur:'1h35',sch:true,tip:"Métro ligne E jusqu'au centre en 30 min environ."},
    SXB:{name:'Strasbourg',country:'France',lat:48.538,lon:7.628,tz:'Europe/Paris',dur:'1h25',sch:true,tip:"Train jusqu'à la gare centrale en 10 min."},
    MUC:{name:'Munich',country:'Allemagne',lat:48.354,lon:11.786,tz:'Europe/Berlin',dur:'1h50',sch:true,tip:"S-Bahn S1 ou S8 jusqu'au centre en 40 min environ."},
    TUN:{name:'Tunis',country:'Tunisie',lat:36.851,lon:10.227,tz:'Africa/Tunis',dur:'2h15',sch:false},
    ZRH:{name:'Zurich',country:'Suisse',lat:47.458,lon:8.548,tz:'Europe/Zurich',dur:'1h35',sch:true,tip:"Train jusqu'à Zurich HB en 12 min."},
    CMN:{name:'Casablanca',country:'Maroc',lat:33.367,lon:-7.590,tz:'Africa/Casablanca',dur:'2h30',sch:false,tip:"Train Al Bidaoui jusqu'au centre."},
    PMI:{name:'Palma',country:'Espagne',lat:39.552,lon:2.739,tz:'Europe/Madrid',dur:'1h25',sch:true},
    LIS:{name:'Lisbonne',country:'Portugal',lat:38.774,lon:-9.134,tz:'Europe/Lisbon',dur:'1h50',sch:true,tip:"Métro ligne rouge, le centre en 25 min environ."},
    HER:{name:'Héraklion',country:'Grèce',lat:35.340,lon:25.180,tz:'Europe/Athens',dur:'3h30',sch:true},
    CFR:{name:'Caen',country:'France',lat:49.173,lon:-0.450,tz:'Europe/Paris',dur:'1h15',sch:true},
    VCE:{name:'Venise',country:'Italie',lat:45.505,lon:12.352,tz:'Europe/Rome',dur:'1h55',sch:true,tip:"Bus ou bateau Alilaguna jusqu'à Venise."},
    ACE:{name:'Lanzarote',country:'Espagne',lat:28.946,lon:-13.605,tz:'Atlantic/Canary',dur:'3h10',sch:true},
    ESU:{name:'Essaouira',country:'Maroc',lat:31.398,lon:-9.682,tz:'Africa/Casablanca',dur:'2h40',sch:false},
    ORN:{name:'Oran',country:'Algérie',lat:35.624,lon:-0.621,tz:'Africa/Algiers',dur:'2h00',sch:false},
    TFS:{name:'Tenerife',country:'Espagne',lat:28.044,lon:-16.572,tz:'Atlantic/Canary',dur:'3h25',sch:true},
    BRI:{name:'Bari',country:'Italie',lat:41.139,lon:16.761,tz:'Europe/Rome',dur:'2h20',sch:true},
    SVQ:{name:'Séville',country:'Espagne',lat:37.418,lon:-5.893,tz:'Europe/Madrid',dur:'1h30',sch:true},
    MXP:{name:'Milan Malpensa',country:'Italie',lat:45.630,lon:8.723,tz:'Europe/Rome',dur:'1h40',sch:true,tip:"Malpensa Express jusqu'à Milano Cadorna en 40 min environ."},
    DBV:{name:'Dubrovnik',country:'Croatie',lat:42.561,lon:18.268,tz:'Europe/Zagreb',dur:'2h20',sch:true},
    RBA:{name:'Rabat',country:'Maroc',lat:34.051,lon:-6.752,tz:'Africa/Casablanca',dur:'2h20',sch:false},
    DSS:{name:'Dakar',country:'Sénégal',lat:14.670,lon:-17.073,tz:'Africa/Dakar',dur:'5h00',sch:false,far:true},
    YUL:{name:'Montréal',country:'Canada',lat:45.470,lon:-73.741,tz:'America/Toronto',dur:'7h45',sch:false,far:true},
    PMO:{name:'Palerme',country:'Italie',lat:38.176,lon:13.091,tz:'Europe/Rome',dur:'2h20',sch:true},
    BSL:{name:'Bâle-Mulhouse',country:'France / Suisse',lat:47.590,lon:7.529,tz:'Europe/Paris',dur:'1h25',sch:true},
    FLR:{name:'Florence',country:'Italie',lat:43.810,lon:11.205,tz:'Europe/Rome',dur:'1h50',sch:true},
    FNC:{name:'Funchal',country:'Portugal',lat:32.698,lon:-16.775,tz:'Atlantic/Madeira',dur:'3h15',sch:true},
    TNG:{name:'Tanger',country:'Maroc',lat:35.727,lon:-5.917,tz:'Africa/Casablanca',dur:'2h00',sch:false},
    OTP:{name:'Bucarest',country:'Roumanie',lat:44.571,lon:26.085,tz:'Europe/Bucharest',dur:'3h10',sch:true},
  },
  // Titre de l'article Wikipédia (en) dont l'image principale (Wikimedia Commons, licence libre) illustre la destination.
  WIKI: {
    LYS:'Lyon', CDG:'Paris', ORY:'Paris', AMS:'Amsterdam', LGW:'London', LTN:'London', MAN:'Manchester', MAD:'Madrid',
    RAK:'Marrakesh', MRS:'Marseille', ALG:'Algiers', NCE:'Nice', BCN:'Barcelona', IST:'Istanbul', GVA:'Geneva',
    DUB:'Dublin', OPO:'Porto', SXB:'Strasbourg', MUC:'Munich', TUN:'Tunis', ZRH:'Zurich', CMN:'Casablanca',
    PMI:'Palma de Mallorca', LIS:'Lisbon', HER:'Heraklion', CFR:'Caen', VCE:'Venice', ACE:'Lanzarote', ESU:'Essaouira',
    ORN:'Oran', TFS:'Tenerife', BRI:'Bari', SVQ:'Seville', MXP:'Milan', DBV:'Dubrovnik', RBA:'Rabat', DSS:'Dakar',
    YUL:'Montreal', PMO:'Palermo', BSL:'Basel', FLR:'Florence', FNC:'Funchal', TNG:'Tangier', OTP:'Bucharest',
  },
  // Repris de index.html : noms lisibles pour les aéroports hors référentiel.
  NAMES: {
    LHR:'Londres Heathrow', STN:'Londres Stansted', LCY:'Londres City', FCO:'Rome', LIN:'Milan Linate', BER:'Berlin',
    ATH:'Athènes', SAW:'Istanbul SAW', AGA:'Agadir', LIL:'Lille', NTE:'Nantes', TLS:'Toulouse', FRA:'Francfort',
    VIE:'Vienne', CPH:'Copenhague', ARN:'Stockholm', OSL:'Oslo', EDI:'Édimbourg', BRS:'Bristol', BHX:'Birmingham',
    BRU:'Bruxelles', CRL:'Charleroi', LUX:'Luxembourg', AJA:'Ajaccio', BIA:'Bastia', FSC:'Figari', CLY:'Calvi',
    NAP:'Naples', CTA:'Catane', OLB:'Olbia', AGP:'Malaga', ALC:'Alicante', VLC:'Valence', IBZ:'Ibiza', MAH:'Minorque',
    FAO:'Faro', LPA:'Gran Canaria', PRG:'Prague', BUD:'Budapest', KRK:'Cracovie', SPU:'Split', CFU:'Corfou', MLA:'Malte',
    DJE:'Djerba', MIR:'Monastir', DOH:'Doha', DXB:'Dubaï', TLV:'Tel Aviv', MPL:'Montpellier', TLN:'Toulon', BES:'Brest',
    RNS:'Rennes', JER:'Jersey', RVN:'Rovaniemi', FDF:'Fort-de-France', SID:'Sal', BVC:'Boa Vista',
  },
  ALIASES: {
    paris:['CDG','ORY'], londres:['LHR','LGW','LTN','STN','LCY'], london:['LHR','LGW','LTN','STN','LCY'],
    milan:['MXP','LIN','BGY'], rome:['FCO','CIA'], istanbul:['IST','SAW'], bale:['BSL'], basel:['BSL'],
    geneve:['GVA'], geneva:['GVA'], tenerife:['TFS','TFN'], majorque:['PMI'], corse:['AJA','BIA','FSC','CLY'],
    maroc:['CMN','RAK','AGA','FEZ','TNG','RBA','ESU'],
  },
};
